[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
preDeployCommand = "python -m database.predeploy"
startCommand = "gunicorn phanta_app:app --bind 0.0.0.0:$PORT --forwarded-allow-ips=\"*\""
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
