"""What an advertising platform connector (Meta Ads, Google Ads) must
provide -- the shape, not the behaviour.

Deliberately a SEPARATE Protocol from flyer_lady.connectors.base's
FlyerLadyConnector, not an extension of it. The two describe
genuinely different products: FlyerLadyConnector's six platforms post
organic content a workshop already owns (a Page, a Business Profile);
this Protocol's platforms spend a workshop's money against a
budget, on a campaign object with its own approval, targeting, and
reporting lifecycle. They share the underlying idea of "a platform
connector" and the SAME activation-state model
(advertising.activation_state), but forcing one Protocol to cover
both would mean either bloating FlyerLadyConnector with
budget/spend/campaign methods no organic platform has, or bloating
this one with publish_step()/fetch_metrics() semantics that don't
fit a campaign's own lifecycle. Two small Protocols, one shared
vocabulary (advertising.capabilities.PlatformCapability), one shared
state machine -- not eight unrelated implementations, and not one
forced-common interface either.

No adapter behind this Protocol makes a real API call yet. Every
concrete method below either isn't implemented yet (Meta Ads,
Google Ads -- both PLANNED, see registry.py) or will be built
against the platform's own genuinely-current API once implementation
starts, not against an assumption of what that API looks like. See
each adapter's own module docstring for what's actually been
verified so far and against what source.
"""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from advertising.capabilities import PlatformCapability


@runtime_checkable
class AdvertisingPlatformConnector(Protocol):
    platform_key: str

    def capabilities(self) -> frozenset[PlatformCapability]:
        """Which of the eleven PlatformCapability values this platform
        actually supports -- not aspirational, not the full ads
        vocabulary by default. A campaign-only adapter with no
        working LEADS support yet must not claim LEADS here."""
        ...

    def authorize_url(self, *, redirect_uri: str, state: str) -> str:
        """Build this platform's OAuth authorization URL. Takes state
        as a parameter, same reasoning as FlyerLadyConnector's own
        method: CSRF state is the caller's concern."""
        ...

    def exchange_code(self, *, code: str, redirect_uri: str) -> dict[str, Any]:
        """Exchange an OAuth authorization code for a token."""
        ...

    def discover_ad_accounts(self, *, token: str) -> list[dict[str, Any]]:
        """List the ad accounts (Meta's act_{id}, Google's
        customer_id) this token can act on. Named distinctly from
        FlyerLadyConnector.discover_accounts() -- an ad account is
        not a Page or a Business Profile location, and conflating the
        two names would misrepresent what's actually being listed."""
        ...

    def revoke(self, session, **kwargs) -> dict[str, Any]:
        """Revoke this platform's connection."""
        ...

    def health(self, session, location_id: int) -> dict[str, Any]:
        """Whether this platform is deployment-configured and this
        location's own connection is healthy."""
        ...

    def create_campaign(self, session, location_id: int, spec: dict[str, Any]) -> Any:
        """Create a campaign. Every adapter behind this Protocol is
        currently PLANNED (see registry.py) -- calling this raises
        NotImplementedError everywhere right now, honestly, rather
        than fabricating a campaign object."""
        ...

    def set_budget(self, session, location_id: int, campaign_id: str, spec: dict[str, Any]) -> Any:
        """Set or update a campaign's budget. Same status as
        create_campaign() -- not implemented on any current adapter."""
        ...

    def fetch_spend(self, session, location_id: int, campaign_id: str) -> Any:
        """Fetch actual spend for a campaign. Same status as
        create_campaign(). Explicit reminder, not enforced by this
        Protocol but binding on every implementation: whatever this
        returns is the ADVERTISER's own spend on THEIR ad account --
        never VANTA revenue, and never to be summed into any VANTA
        billing/revenue figure."""
        ...

    def fetch_analytics(self, session, location_id: int, campaign_id: str) -> Any:
        """Fetch campaign-level performance analytics."""
        ...

    def fetch_leads(self, session, location_id: int, campaign_id: str) -> Any:
        """Fetch leads generated by a campaign, for platforms and
        campaign objectives that support lead capture. Not every
        campaign objective does -- an adapter must check its own
        campaign's objective before claiming this worked, not assume
        every campaign is a leads campaign."""
        ...
