


# Prepare booking data for repository
booking_data = {
    "booking_reference": booking_reference,
    "location_id": location["location_id"],
    "location_id": location["id"],
    "company": location["location_name"],
    "location": location["name"],
    "customer_id": customer_id,
    "service_id": service_id,
    "first_name": (form_data.get("first_name") or "").strip(),
    "surname": (form_data.get("surname") or "").strip(),
    "customer_email": (form_data.get("customer_email") or form_data.get("email") or "").strip(),
    "phone": phone,
    "preferred_contact_method": (form_data.get("preferred_contact_method") or "WhatsApp").strip(),
    "make": (form_data.get("make") or "").strip(),
    "model": (form_data.get("model") or "").strip(),
    "vehicle_year": (form_data.get("vehicle_year") or "").strip(),
    "fuel_type": (form_data.get("fuel_type") or "").strip(),
    "registration_number": (form_data.get("registration_number") or "").strip(),
    "colour": (form_data.get("colour") or "").strip(),
    "vehicle_vin": (form_data.get("vehicle_vin") or "").strip(),
    "service": service,
    "service_level": service_level,
    "current_mileage": (form_data.get("current_mileage") or "").strip(),
    "scheduled_date": scheduled_date,
    "date": scheduled_date,
    "status": status,
    "service_due_date": service_due_date,
    "work_to_be_done": (form_data.get("work_to_be_done") or form_data.get("work") or "").strip(),
    "public_notes": (form_data.get("public_notes") or "").strip(),
    "internal_notes": (form_data.get("internal_notes") or "").strip(),
    "source": source,
    "quote_declined": (form_data.get("quote_declined") or "No").strip(),
    "contacted": "No",
    "whatsapp_opt_in": db_bool(form_data.get("whatsapp_opt_in", "false")),
    "privacy_consent_at": (now if boolish(form_data.get("privacy_consent", "false")) else None),
    "reminder_opt_in": db_bool(form_data.get("reminder_opt_in", "true")),
    "completed_at": completed_at,
    "created_at": now,
    "updated_at": now,
}