/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal installs. It is committed here so
// TypeScript has the expected ambient types before dependencies are installed.
