"""
===============================================================================
PHANTA Dependency Auditor v2.0
HTML Report Exporter
===============================================================================

Exports dependency audit results as a standalone HTML report.

Responsibilities
----------------
• Generate HTML reports
• Write HTML reports to disk

This module performs NO analysis.
"""

from __future__ import annotations

from html import escape
from pathlib import Path

from .models import AuditReport, Statistics


# =============================================================================
# HTML Report Exporter
# =============================================================================

class HtmlReportExporter:
    """
    Exports audit results as a standalone HTML report.
    """

    # -------------------------------------------------------------------------

    def to_html(
        self,
        report: AuditReport,
        statistics: Statistics,
    ) -> str:
        """
        Generate a complete HTML report.
        """

        def section(title: str, body: str) -> str:
            return f"""
<section class="card">
<h2>{escape(title)}</h2>
{body}
</section>
"""

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>PHANTA Dependency Audit Report</title>

<style>

body {{
    font-family: Arial, Helvetica, sans-serif;
    background:#f4f4f4;
    color:#222;
    margin:40px;
}}

h1 {{
    margin-bottom:0;
}}

.card {{
    background:white;
    padding:20px;
    margin-top:20px;
    border-radius:8px;
    box-shadow:0 2px 6px rgba(0,0,0,.08);
}}

table {{
    width:100%;
    border-collapse:collapse;
}}

th, td {{
    padding:8px;
    border-bottom:1px solid #ddd;
    text-align:left;
}}

th {{
    background:#efefef;
}}

.good {{
    color:green;
}}

.warning {{
    color:#b8860b;
}}

.bad {{
    color:red;
}}

code {{
    background:#eee;
    padding:2px 4px;
    border-radius:3px;
}}

</style>

</head>

<body>

<h1>PHANTA Dependency Audit Report</h1>

<p>
Generated by Dependency Auditor v2.0
</p>

{section(
"Summary",
f'''
<table>
<tr><th>Metric</th><th>Value</th></tr>
<tr><td>Modules</td><td>{statistics.modules}</td></tr>
<tr><td>Dependencies</td><td>{statistics.dependencies}</td></tr>
<tr><td>Average Dependencies</td><td>{statistics.average_dependencies:.2f}</td></tr>
<tr><td>Health Score</td><td><strong>{statistics.health_score}/100</strong></td></tr>
</table>
'''
)}

{section(
"Analysis",
f'''
<table>
<tr><th>Check</th><th>Count</th></tr>
<tr><td>Syntax Errors</td><td>{statistics.syntax_errors}</td></tr>
<tr><td>Import Issues</td><td>{statistics.import_issues}</td></tr>
<tr><td>Duplicate Imports</td><td>{statistics.duplicate_imports}</td></tr>
<tr><td>Circular Dependencies</td><td>{statistics.cycles}</td></tr>
<tr><td>Architecture Violations</td><td>{statistics.architecture_violations}</td></tr>
</table>
'''
)}

{section(
"Dependency Metrics",
f'''
<table>
<tr><th>Metric</th><th>Value</th></tr>
<tr>
<td>Most Imports</td>
<td>{escape(statistics.most_imports_module)} ({statistics.most_imports_count})</td>
</tr>

<tr>
<td>Most Imported Module</td>
<td>{escape(statistics.most_depended_module)} ({statistics.most_depended_count})</td>
</tr>
</table>
'''
)}

{section(
"Syntax Errors",
"<ul>" + "".join(
f"<li><code>{escape(issue.module)}</code> "
f"(line {issue.line}) - "
f"{escape(issue.message)}</li>"
for issue in report.syntax
) + "</ul>"
if report.syntax else
"<p class='good'>No syntax errors detected.</p>"
)}

{section(
"Import Issues",
"<ul>" + "".join(
f"<li><code>{escape(issue.module)}</code> "
f"(line {issue.line}) - "
f"{escape(issue.issue)}</li>"
for issue in report.imports
) + "</ul>"
if report.imports else
"<p class='good'>No import issues detected.</p>"
)}

{section(
"Duplicate Imports",
"<ul>" + "".join(
f"<li><code>{escape(item.module)}</code> "
f"(line {item.line}) - "
f"{escape(item.import_name)}</li>"
for item in report.duplicates
) + "</ul>"
if report.duplicates else
"<p class='good'>No duplicate imports detected.</p>"
)}

{section(
"Circular Dependencies",
"<ul>" + "".join(
f"<li>{escape(' → '.join(c.modules))}</li>"
for c in report.cycles
) + "</ul>"
if report.cycles else
"<p class='good'>No circular dependencies detected.</p>"
)}

{section(
"Architecture Violations",
"<ul>" + "".join(
f"<li><code>{escape(v.source_module)}</code> → "
f"<code>{escape(v.target_module)}</code><br>"
f"{escape(v.description)}</li>"
for v in report.architecture
) + "</ul>"
if report.architecture else
"<p class='good'>No architecture violations detected.</p>"
)}

</body>
</html>
"""

        return html

    # -------------------------------------------------------------------------

    def write(
        self,
        filename: str | Path,
        report: AuditReport,
        statistics: Statistics,
    ) -> Path:
        """
        Write an HTML report to disk.
        """

        path = Path(filename)

        path.write_text(
            self.to_html(
                report,
                statistics,
            ),
            encoding="utf-8",
        )

        return path


# =============================================================================
# Convenience Functions
# =============================================================================

def export_html(
    filename: str | Path,
    report: AuditReport,
    statistics: Statistics,
) -> Path:
    """
    Export an HTML report.
    """

    return HtmlReportExporter().write(
        filename,
        report,
        statistics,
    )


def report_as_html(
    report: AuditReport,
    statistics: Statistics,
) -> str:
    """
    Return the report as an HTML string.
    """

    return HtmlReportExporter().to_html(
        report,
        statistics,
    )